# Generated by Django 4.2 on 2026-02-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
