# Generated by Django 4.2 on 2026-02-18 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0003_post_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="retweets",
            field=models.ManyToManyField(
                blank=True, related_name="retweeted_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
