# Generated by Django 6.0.1 on 2026-01-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="banner_image",
            field=models.ImageField(blank=True, null=True, upload_to="banners/"),
        ),
    ]
