# Generated by Django 6.0.1 on 2026-01-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_banner_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="social_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="social_provider",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
