# Generated by Django 4.2 on 2026-02-01 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_social_provider_user_provider_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="provider",
            new_name="social_provider",
        ),
        migrations.RemoveField(
            model_name="user",
            name="following",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_verified",
        ),
        migrations.AddField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="following", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="social_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
